### ISSUE TITLE
Couldn't run the script

### ISSUE THREAD

**Issue by lahiiru** [scivision/pyoptflow#1]
```
  File "HornSchunck.py", line 22
    fn1 = f'{stem}.{i}{ext}'
                           ^
SyntaxError: invalid syntax
```
Above error appears when `python HornSchunck.py data/box/box`. Tested in Windows and Ubuntu, python 2.7

**Comment by scienceopen** [comment]
Yes this is current Python (>= 3.6) string syntax

**Comment by lahiiru** [comment]
Thanks. Managed to fix using string.format()

**Comment by wrat** [comment]
@lahiiru  
I am facing same problem , can you give me fix code snippet here ???

**Comment by scivision** [comment]
I can change this to Python<3.6 format tonight. Thanks

**Comment by wrat** [comment]
@scivision  have you changed the code ???

**Comment by lahiiru** [comment]
`fn1 = "{0}.{1}{2}".format(stem,i,ext)`

replace other lines also accordingly.

**Comment by wrat** [comment]
@lahiiru  after changing this it's showing another error 
  File "LucasKanade.py", line 11, in <module>
    from pyoptflow import LucasKanade, getPOI, gaussianWeight
  File "/home/abhishek/pyoptflow-master/pyoptflow/__init__.py", line 74
    Vpt = np.linalg.inv(A.T @ W**2 @ A) @ A.T @ W**2 @ B
                            ^
SyntaxError: invalid syntax
??

**Comment by lahiiru** [comment]
@wrat 

Then replace pyoptflow/init.py", line 74 to
`Vpt = np.linalg.inv(A.T.dot(W**2).dot(A)).dot(A.T).dot(W**2).dot(B)`

**Comment by scivision** [comment]
This has been updated to version "1.1.0" which is Python >= 3.5 compatible
