### ISSUE TITLE
Flipped output 

### ISSUE THREAD

**Issue by VictorZuanazzi** [scivision/pyoptflow#3]
Hey,

Nice code!

The output is flipped. You probably have noticed. I fixed that with a simple np.flip.

```
im1 = np.flip(im1, 0)
im2 = np.flip(im2, 0)
```

**Comment by scivision** [comment]
`im1.T` might give the same effect. I don't modify the image orientations, it's just what comes from imageio.imread(), perhaps the most popular library for that task.
